"""'147'

Revision ID: 592d6832adc0
Revises: 36af5227a7af
Create Date: 2017-03-01 19:59:29.417000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592d6832adc0'
down_revision = '36af5227a7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
